Villa_project/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace Villa_project.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Contact()
        {
            return View();
        }

        public IActionResult Creator()
        {
            return View();
        }

    }
}

Villa_project/Controllers/AmenityController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Villa_project.Application.Common.Interfaces;
using Villa_project.Application.Common.Utility;
using Villa_project.Domain.Entities;
using Villa_project.ViewModels;

namespace Villa_project.Controllers
{
    [Authorize(Roles =SD.Role_Admin)]
    public class AmenityController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;


        public AmenityController(IUnitOfWork unit)
        {
            _unitOfWork=unit;
        }
        public IActionResult Index()
        {
            var amentiesInDb = _unitOfWork.amenity.GetAll(includeProperties: "Villa");
            return View(amentiesInDb);
        }

        public IActionResult Create()
        {
            /* IEnumerable<SelectListItem> list = _db.Villas.ToList().Select(
                 u => new SelectListItem
                 {
                     Text = u.Name, // this will be options in drop down
                     Value=u.Id.ToString()
                 }
                 );

             ViewData["Villa List"]=list;*/

            AmenityVM amenityVM = new()
            {
                Amenity = new Amenity(), // ensures model binding works properly
                Villalist = _unitOfWork.villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                })
            };

            return View(amenityVM);

        }

        [HttpPost]
        public IActionResult Create(AmenityVM obj)
        {

    
            if (obj == null) return BadRequest();

            ModelState.Remove("Villa");
            if (ModelState.IsValid )
            {
                _unitOfWork.amenity.Add(obj.Amenity);
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }


           


            obj.Villalist= _unitOfWork.villa.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });

            return View(obj);

        }


        public IActionResult Update(int amenityId)
        {
           AmenityVM amenityVM = new()
            {

                Villalist =  _unitOfWork.villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),

                Amenity=_unitOfWork.amenity.Get(u => u.Id==amenityId)
            };
            if (amenityVM.Amenity==null)
            {
                return NotFound();
            }

            return View(amenityVM);
        }

        [HttpPost]
        public IActionResult Update(AmenityVM amenityVM)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.amenity.Update(amenityVM.Amenity);
                _unitOfWork.Save();
                TempData["success"]="The villa have been updated";
                return RedirectToAction("Index");
            }
            amenityVM.Villalist= _unitOfWork.villa.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            return View(amenityVM);
        }

        public IActionResult Delete(int amenityId)
        {
            AmenityVM amenityVM = new()
            {

                Villalist =  _unitOfWork.villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),

                Amenity=_unitOfWork.amenity.Get(u => u.Id==amenityId)
            };
            if (amenityVM.Amenity==null)
            {
                return NotFound();
            }

            return View(amenityVM);
        }


        [HttpPost]
        [ValidateAntiForgeryToken] // recommended for security
        public IActionResult Delete(AmenityVM amenityVM)
        {
            Amenity? amenityInDb = _unitOfWork.amenity.Get(u => u.Id == amenityVM.Amenity.Id);

            if (amenityInDb != null)
            {
                _unitOfWork.amenity.Remove(amenityInDb);
                _unitOfWork.Save();
                TempData["success"] = "The villa has been deleted";
                return RedirectToAction("Index");
            }

            TempData["error"] = "The villa deletion failed";
            return View(amenityVM);
        }
    }
}

Villa_project/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using Villa_project.Application.Common.Interfaces;
using Villa_project.Application.Common.Utility;
using Villa_project.Infrastructure.Repository;
using Villa_project.ViewModels;

namespace Villa_project.Controllers
{
    public class DashboardController : Controller
    {
        private readonly IUnitOfWork _unitOfwork;
        static int previousMonth = DateTime.Now.Month==1 ? 12 : DateTime.Now.Month-1;
        readonly DateTime previousMonthStartDate = new DateTime(DateTime.Now.Year, previousMonth, 1);
        readonly DateTime currentMonthStartDate = new DateTime(DateTime.Now.Year, DateTime.Now.Month , 1);
        public DashboardController(IUnitOfWork unitOfWork)
        {
            _unitOfwork=unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetTotalBookingRadialChartData()
        {
            var totalbooking = _unitOfwork.Booking.GetAll(u => u.Status!=SD.StatusPending
            || u.Status==SD.StatusCancelled);

            var countByCurrentMonth = totalbooking.Count(u => u.BookingDate>=currentMonthStartDate &&
            u.BookingDate<=DateTime.Now);

            var countByPreviousMonth = totalbooking.Count(u => u.BookingDate>=previousMonthStartDate &&
          u.BookingDate<=currentMonthStartDate);

            return Json(GetRadialChartDataModel(totalbooking.Count(), countByCurrentMonth, countByPreviousMonth));
        }

        public async Task<IActionResult> GetRegisteredUserChartData()
        {
            var totalUser = _unitOfwork.User.GetAll();

            var countByCurrentMonth = totalUser.Count(u => u.CreatedAt>=currentMonthStartDate &&
            u.CreatedAt<=DateTime.Now);

            var countByPreviousMonth = totalUser.Count(u => u.CreatedAt>=previousMonthStartDate &&
          u.CreatedAt<=currentMonthStartDate);

          

            return Json(GetRadialChartDataModel(totalUser.Count(),countByCurrentMonth,countByPreviousMonth));

        }

        public async Task<IActionResult> GetRevenueChartData()
        {

            var totalbooking = _unitOfwork.Booking.GetAll(u => u.Status!=SD.StatusPending
           || u.Status==SD.StatusCancelled);

            var totalRevenue =Convert.ToInt32(totalbooking.Sum(u => u.TotalCost));


            var totalUser = _unitOfwork.User.GetAll();

            var countByCurrentMonth = totalbooking.Where(u => u.BookingDate>=currentMonthStartDate &&
u.BookingDate<=DateTime.Now).Sum(u=>u.TotalCost);

            var countByPreviousMonth = totalbooking.Where(u => u.BookingDate>=previousMonthStartDate &&
          u.BookingDate<=currentMonthStartDate).Sum(u => u.TotalCost);



            return Json(GetRadialChartDataModel(totalRevenue, countByCurrentMonth, countByPreviousMonth));

        }


        public async Task<IActionResult> GetBookingPieChartData()
        {
            var totalbooking = _unitOfwork.Booking.GetAll(  u => u.BookingDate>=DateTime.Now.AddDays(-30) && ( u.Status!=SD.StatusPending
            || u.Status==SD.StatusCancelled));


            var customerWithOneBooking = totalbooking.GroupBy(u => u.UserId).Where(x => x.Count()==1).Select(x=>x.Key).ToList();

            int bookingsByNewCustomer = customerWithOneBooking.Count();
            int bookingsByReturningCustomer = totalbooking.Count()-bookingsByNewCustomer;

            PieChartVM pieChartVM = new()
            {
                Labels=new string[] { "New Customers", "Returning Customer" },
                Series=new decimal[] { bookingsByNewCustomer, bookingsByReturningCustomer }
            };

           
            return Json(pieChartVM);
        }

        public async Task<LineChartVM> GetMemberAndBookingLineChartData()
        {
            var bookingData = _unitOfwork.Booking.GetAll(u => u.BookingDate >= DateTime.Now.AddDays(-30) &&
             u.BookingDate.Date <= DateTime.Now)
                 .GroupBy(b => b.BookingDate.Date)
                 .Select(u => new {
                     DateTime = u.Key,
                     NewBookingCount = u.Count()
                 });

            var customerData = _unitOfwork.User.GetAll(u => u.CreatedAt >= DateTime.Now.AddDays(-30) &&
            u.CreatedAt.Date <= DateTime.Now)
                .GroupBy(b => b.CreatedAt.Date)
                .Select(u => new {
                    DateTime = u.Key,
                    NewCustomerCount = u.Count()
                });


            var leftJoin = bookingData.GroupJoin(customerData, booking => booking.DateTime, customer => customer.DateTime,
                (booking, customer) => new
                {
                    booking.DateTime,
                    booking.NewBookingCount,
                    NewCustomerCount = customer.Select(x => x.NewCustomerCount).FirstOrDefault()
                });


            var rightJoin = customerData.GroupJoin(bookingData, customer => customer.DateTime, booking => booking.DateTime,
                (customer, booking) => new
                {
                    customer.DateTime,
                    NewBookingCount = booking.Select(x => x.NewBookingCount).FirstOrDefault(),
                    customer.NewCustomerCount
                });

            var mergedData = leftJoin.Union(rightJoin).OrderBy(x => x.DateTime).ToList();

            var newBookingData = mergedData.Select(x => x.NewBookingCount).ToArray();
            var newCustomerData = mergedData.Select(x => x.NewCustomerCount).ToArray();
            var categories = mergedData.Select(x => x.DateTime.ToString("MM/dd/yyyy")).ToArray();

            List<ChartData> chartDataList = new()
            {
                new ChartData
                {
                    Name = "New Bookings",
                    Data = newBookingData
                },
                new ChartData
                {
                    Name = "New Members",
                    Data = newCustomerData
                },
            };

            LineChartVM lineChart = new()
            {
                Categories = categories,
                Series = chartDataList
            };

            return lineChart;
        }


        private static RadialBarChartVM GetRadialChartDataModel(int totalCount,double currentMonthCount,double prevMonthCount)
        {
            RadialBarChartVM radialBarChartVM = new();

            int increaseDecreaseRatio = 100;
            if (prevMonthCount!=0)
            {
                increaseDecreaseRatio=Convert.ToInt32((currentMonthCount-prevMonthCount)/ prevMonthCount* 100);

            }

            radialBarChartVM.TotalCount=totalCount;
            radialBarChartVM.CountInCurrentMonth=Convert.ToInt32(currentMonthCount);
            radialBarChartVM.HasRatioIncreased= currentMonthCount>prevMonthCount;
            radialBarChartVM.Series=new int[] { increaseDecreaseRatio };

            return radialBarChartVM;
        }
    }
}

Villa_project/Controllers/VillaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Villa_project.Application.Common.Interfaces;
using Villa_project.Domain.Entities;
using Villa_project.Infrastructure.Data;

namespace Villa_project.Controllers
{
    [Authorize]
    public class VillaController : Controller
    {
        //   private readonly ApplicationDbContext _db;   for simple

        //using generic repository

        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public VillaController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork=unitOfWork;
            _webHostEnvironment=webHostEnvironment;
        }

        public IActionResult Index()
        {
            var villas =_unitOfWork.villa.GetAll();
            return View(villas);
        }

        public IActionResult Edit(int villaId)
        {
            if (villaId==null) return View();

            //var villaInDb = _db.Villas.Find(villaId);
            // for filter we use where
            //_db.Villas.Where(u => u.Id>4);

            var villaInDb= _unitOfWork.villa.Get(u=>u.Id==villaId);
            if(villaInDb==null)
            {
                return RedirectToAction("Error","Home");
            }
            return View(villaInDb);
        }
        [HttpPost]
        public IActionResult Edit(Villa villa)
        {

            if (ModelState.IsValid && villa.Id>0)
            {
                if (villa.Image!=null)
                {
                    string fileName = Guid.NewGuid().ToString()+ Path.GetExtension(villa.Image.FileName);
                    string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, @"images\Villa");

                    if(!string.IsNullOrEmpty(villa.ImageUrl))
                    {
                        var oldImagePath=Path.Combine(_webHostEnvironment.WebRootPath,villa.ImageUrl.TrimStart('\\'));
                        if(System.IO.File.Exists(oldImagePath)) 
                            {
                               System.IO.File.Delete(oldImagePath);
                            }

                    }

                    using var filestream = new FileStream(Path.Combine(imagePath, fileName), FileMode.Create);

                    villa.Image.CopyTo(filestream);
                    villa.ImageUrl=@"\images\Villa\"+fileName;
                }
               
                _unitOfWork.villa.Update(villa);
                _unitOfWork.Save();
                TempData["success"]="The data have been updated";
                return RedirectToAction("Index");
            }
            TempData["error"]="The data have not been updated";
            return View(villa);
        }
        
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Villa villa)
        {

            if(villa.Name==villa.Description)
            {
                ModelState.AddModelError("name", "The name and description cannot be same");
            }


            if (ModelState.IsValid)
            {

               if(villa.Image!=null)
                {
                    string fileName = Guid.NewGuid().ToString()+ Path.GetExtension(villa.Image.FileName);
                    string imagePath = Path.Combine(_webHostEnvironment.WebRootPath, @"images\Villa");

                    using var filestream = new FileStream(Path.Combine(imagePath, fileName), FileMode.Create); 

                    villa.Image.CopyTo(filestream);
                    villa.ImageUrl=@"\images\Villa\"+fileName;
                }
                else
                {
                    villa.ImageUrl="Add Default image";
                }
                 _unitOfWork.villa.Add(villa);
                _unitOfWork.Save();

                return RedirectToAction("Index");
            }

            return View(villa);
        }

        public IActionResult Delete(int villaId)
        {
            if (villaId==null) return NotFound();

            var villaInDb = _unitOfWork.villa.Get(u => u.Id==villaId);

            return View(villaInDb);
          
        }

        [HttpPost]
        public IActionResult Delete(Villa villa)
        {
            
            var villaInDb = _unitOfWork.villa.Get(u=>u.Id==villa.Id);

            if (villaInDb is not null)
            {
                if (!string.IsNullOrEmpty(villa.ImageUrl))
                {
                    var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, villa.ImageUrl.TrimStart('\\'));
                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }

                }
                _unitOfWork.villa.Remove(villaInDb);
                _unitOfWork.Save();
                TempData["Success"]="The data has been deleted";
                return RedirectToAction("Index");
            }

            TempData["error"]="The data has not been deleted";
            return View();
        } 


    }
}

Villa_project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Villa_project</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.1/css/bootstrap.min.css" crossorigin="anonymous" />

    <!-- Icons & Animations -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />

    <!-- Toastr + DataTables -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />

    <!-- Custom -->
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Villa_project.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/spinner.css" />

    <style>
        /* Gradient Text */
        .text-gradient {
            background: linear-gradient(45deg, #ff6ec4, #7873f5);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            transition: all .3s ease;
        }

            .text-gradient:hover {
                opacity: 0.8;
                transform: scale(1.05);
            }

        /* Navbar */
        .glass-nav {
            background: rgba(20, 20, 20, 0.8) !important;
            backdrop-filter: blur(12px);
            transition: background 0.4s ease-in-out;
        }

            .glass-nav:hover {
                background: rgba(30, 30, 30, 0.9) !important;
            }

        /* Nav links */
        .nav-hover {
            position: relative;
            transition: all .3s ease-in-out;
        }

            .nav-hover::after {
                content: '';
                position: absolute;
                bottom: -5px;
                left: 0;
                width: 0%;
                height: 2px;
                background: linear-gradient(90deg, #ff6ec4, #7873f5);
                transition: width .3s ease-in-out;
            }

            .nav-hover:hover::after {
                width: 100%;
            }

            .nav-hover:hover {
                transform: translateY(-2px);
                color: #ffb347 !important;
            }

        /* Dropdown */
        .dropdown-menu-dark {
            border-radius: 12px;
            animation: fadeInDown .4s;
        }

        /* Card / Content */
        main {
            animation: fadeInUp .6s;
        }

        /* Footer */
        footer {
            padding: 15px 0;
            font-size: 0.9rem;
            background: linear-gradient(90deg, #141E30, #243B55);
            color: #ddd;
            letter-spacing: .5px;
        }

            footer i {
                color: #ff6ec4;
            }

        /* Spinner overlay */
        .spinner {
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            z-index: 1050;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark glass-nav shadow-lg border-bottom border-secondary animate__animated animate__fadeInDown">
            <div class="container-fluid">
                <!-- Logo -->
                <a class="navbar-brand d-flex align-items-center gap-2 fw-bold text-gradient" asp-controller="Home" asp-action="Index">
                    <img src="~/Images/resort.png" style="width:35px" alt="logo" class="animate__animated animate__zoomIn" />
                    VillaVerse
                </a>

                <!-- Mobile Toggle -->
                <button class="navbar-toggler border-0 shadow-none" type="button" data-bs-toggle="collapse" data-bs-target="#mainNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Menu -->
                <div class="collapse navbar-collapse justify-content-end animate__animated animate__fadeIn" id="mainNavbar">
                    <ul class="navbar-nav gap-3 align-items-center">
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle nav-hover fw-semibold" href="#" data-bs-toggle="dropdown">
                                    Management
                                </a>
                                <ul class="dropdown-menu dropdown-menu-dark shadow-lg rounded-3">
                                    <li><a class="dropdown-item" asp-controller="Villa" asp-action="Index">Villa</a></li>
                                    <li><a class="dropdown-item" asp-controller="VillaNumber" asp-action="Index">Villa Number</a></li>
                                    <li><a class="dropdown-item" asp-controller="Amenity" asp-action="Index">Amenity</a></li>
                                    <li><a class="dropdown-item" asp-controller="Booking" asp-action="Index" asp-route-status="@SD.StatusApproved">Booking</a></li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li><a class="dropdown-item" href="#">More Options</a></li>
                                </ul>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link nav-hover fw-semibold" asp-controller="Booking" asp-action="Index">My Booking</a>
                            </li>
                        }

                        <li class="nav-item"><a class="nav-link nav-hover fw-semibold" asp-controller="About" asp-action="Index">About</a></li>
                        <li class="nav-item"><a class="nav-link nav-hover fw-semibold" asp-controller="About" asp-action="Contact">Contact Us</a></li>
                        <li class="nav-item"><a class="nav-link nav-hover fw-semibold" asp-controller="About" asp-action="Creator">Created By</a></li>

                        <partial name="_LoginPartial" />
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div>
        <main role="main" class="container py-4">
            <div class="loading spinner" style="display:none;"></div>
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="text-center animate__animated animate__fadeInUp">
        Made by <i class="bi bi-emoji-smile"></i> Akshay Kumar
    </footer>

    <!-- Scripts -->
    <script src="~/lib/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.1/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.1/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Villa_project/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WhiteLagoon.Web</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.1/css/bootstrap.min.css" integrity="sha512-Z/def5z5u2aR89OuzYcxmDJ0Bnd5V1cKqBEbvLOiUNWdg9PQeXVvXLI90SE4QOHGlfLqUnDNVAYyZi8UwUTmWQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/WhiteLagoon.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/spinner.css" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/css/apexcharts.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow">
            <div class="container-fluid d-flex justify-content-between">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/resort.png" style="width:35px" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <partial name="_LoginPartialAdmin" />
        </nav>
    </header>
    <div class="container-fluid">
        <div class="loading spinner" style="display:none;"></div>
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-dark sidebar collapse">
                <div class="position-static pt-3">
                    <ul class="navbar-nav">
                        <li>
                            <div class="text-muted small fw-bold text-uppercase px-3">
                                Menu
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Dashboard" asp-action="Index">
                                <span class="me-2"><i class="bi bi-speedometer2"></i></span>
                                <span>Dashboard</span>
                            </a>
                        </li>
                        <li>
                            <div class="text-muted small fw-bold text-uppercase px-3 mt-2">
                                Content Management
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Villa" asp-action="Index">
                                <span class="me-2"><i class="bi bi-house-door"></i></span>
                                <span>Villa</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="VillaNumber" asp-action="Index">
                                <span class="me-2"><i class="bi bi-list-ol"></i></i></span>
                                <span>VillaNumber</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Amenity" asp-action="Index">
                                <span class="me-2"><i class="bi bi-building"></i></span>
                                <span>Amenity</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Booking" asp-action="Index" asp-route-status="@SD.StatusApproved">
                                <span class="me-2"><i class="bi bi-journal-plus"></i></span>
                                <span>Booking</span>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="About" asp-action="Index">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="About" asp-action="Contact">Contact US</a>
                        </li>
                    </ul>
                </div>
            </nav>
            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 w-100">
                    <partial name="_Notification" />
                    @RenderBody()
                </div>
            </main>
        </div>
    </div>

    <footer class="border-top footer bg-dark text-muted">
        <div class="container text-center">
            Made with <i class="bi bi-heart-fill"></i> by Akshay Kumar
        </div>
    </footer>
    @* jquery-ajax-unobtrusive@3.2.6 *@

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.0.1/js/bootstrap.bundle.min.js" integrity="sha512-sH8JPhKJUeA9PWk3eOcOl8U+lfZTgtBXD41q6cO/slwxGHCxKcW45K4oPCUhHG7NMB4mbKEddVmPuTXtpbCbFA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    @*  <script src="~/js/jquery.unobtrusive-ajax.min.js"></script> *@
    <script src="~/js/apexcharts.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>