Villa_project/Controllers/VillaNumberController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Runtime.InteropServices.Marshalling;
using Villa_project.Application.Common.Interfaces;
using Villa_project.Domain.Entities;
using Villa_project.Infrastructure.Data;
using Villa_project.ViewModels;

namespace Villa_project.Controllers
{
    public class VillaNumberController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        

        public VillaNumberController(IUnitOfWork unit)
        {
            _unitOfWork=unit;
        }
        public IActionResult Index()
        {
            var villasNumberInDb = _unitOfWork.villaNumber.GetAll(includeProperties:"Villa");
            return View(villasNumberInDb);
        }

        public IActionResult Create()
        {
            /* IEnumerable<SelectListItem> list = _db.Villas.ToList().Select(
                 u => new SelectListItem
                 {
                     Text = u.Name, // this will be options in drop down
                     Value=u.Id.ToString()
                 }
                 );

             ViewData["Villa List"]=list;*/

            VillaNumberVM villaNumberVM = new()
            {
                VillaNumber = new VillaNumber(), // ensures model binding works properly
                Villalist = _unitOfWork.villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                })
            };

            return View(villaNumberVM);
      
        }

        [HttpPost]
        public IActionResult Create(VillaNumberVM obj)
        {

           bool exist = _unitOfWork.villaNumber.Any(u => u.Villa_Number == obj.VillaNumber.Villa_Number);
            if (obj == null) return BadRequest();

             ModelState.Remove("Villa");
             if (ModelState.IsValid && !exist)
             {
                _unitOfWork.villaNumber.Add(obj.VillaNumber);
                _unitOfWork.Save();
                 return RedirectToAction("Index");
             }
           

            if (exist)
            {
                TempData["error"]="Villa already exist ";
            }


            obj.Villalist= _unitOfWork.villa.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });

             return View(obj);
           
        }


        public IActionResult Update(int villaId)
        {
            VillaNumberVM villaNumberVM = new()
            {

                Villalist =  _unitOfWork.villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),

                VillaNumber=_unitOfWork.villaNumber.Get(u => u.Villa_Number==villaId)
            };
            if(villaNumberVM.VillaNumber==null)
            {
                return NotFound();
            }

            return View(villaNumberVM);
        }

        [HttpPost]
        public IActionResult Update(VillaNumberVM villaNumberVM)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.villaNumber.Update(villaNumberVM.VillaNumber);
                _unitOfWork.Save();
                TempData["success"]="The villa have been updated";
                return RedirectToAction("Index");
            }
            villaNumberVM.Villalist= _unitOfWork.villa.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            return View(villaNumberVM);
        }

        public IActionResult Delete(int villaId)
        {
            VillaNumberVM villaNumberVM = new()
            {

                Villalist =  _unitOfWork.villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),

                VillaNumber=_unitOfWork.villaNumber.Get(u => u.Villa_Number==villaId)
            };
            if (villaNumberVM.VillaNumber==null)
            {
                return NotFound();
            }

            return View(villaNumberVM);
        }


        [HttpPost]
        [ValidateAntiForgeryToken] // recommended for security
        public IActionResult Delete(VillaNumberVM villaNumberVM)
        {
            var villaInDb = _unitOfWork.villaNumber.Get(u => u.Villa_Number == villaNumberVM.VillaNumber.Villa_Number);

            if (villaInDb != null)
            {
                _unitOfWork.villaNumber.Remove(villaInDb);
                _unitOfWork.Save();
                TempData["success"] = "The villa has been deleted";
                return RedirectToAction("Index");
            }

            TempData["error"] = "The villa deletion failed";
            return View(villaNumberVM);
        }


    }
}

Villa_project/Views/VillaNumber/Create.cshtml
@model Villa_project.ViewModels.VillaNumberVM

<div class="w-100 card border-0 p-4">
<div class="card-header bg-success bg-gradient ml-0 py-3">
    <div class="row">
        <div class="col-12 text-center">
            <h2 class="text-white py-2">Create Villa</h2>
        </div>
    </div>
</div>
<div class="card-body border p-4">
    <form method="post" class="row" enctype="multipart/form-data">
        <div class="p-3">
            @* <div asp-validation-summary="All"></div> to add custom validation from controller  *@ 
            <div class="form-floating py-1 col-12">
               <select asp-for="@Model.VillaNumber.VillaId" asp-items="@Model.Villalist" class="form-select border shadow">

                   <option disabled selected> Select Villa</option>

               </select>
                <label asp-for="VillaNumber.VillaId" class="ms-2"></label>
                <span asp-validation-for="VillaNumber.VillaId" class="text-danger"></span>
            </div>
            <div class="form-floating py-1 col-12">
                    <input asp-for="VillaNumber.Villa_Number" class="form-control border shadow" />
                    <label asp-for="VillaNumber.Villa_Number" class="ms-2"></label>
                    <span asp-validation-for="VillaNumber.Villa_Number" class="text-danger"></span>
            </div>
            <div class="form-floating py-1 col-12">
                    <input asp-for="VillaNumber.SpecialDetails" class="form-control border shadow" />
                    <label asp-for="VillaNumber.SpecialDetails" class="ms-2"></label>
                    <span asp-validation-for="VillaNumber.SpecialDetails" class="text-danger"></span>
            </div>
            <div class="row pt-2">
                <div class="col-6 col-md-3">
                    <button type="submit" class="btn btn-success w-100">
                        <i class="bi bi-check-circle"></i> Create
                    </button>
                </div>
                <div class="col-6 col-md-3">
                    <a asp-controller="VillaNumber" asp-action="Index" class="btn btn-secondary w-100">
                        <i class="bi bi-x-circle"></i> Cancel
                    </a>
                </div>
            </div>
        </div>
    </form>
</div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Villa_project/Views/VillaNumber/Delete.cshtml
@model Villa_project.ViewModels.VillaNumberVM

@{
    ViewData["Title"] = "Delete Villa Number";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />

<div class="w-100 card border-0 p-4 shadow-lg rounded">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2 text-uppercase">Delete Villa</h2>
            </div>
        </div>
    </div>

    <div class="card-body border p-4">
        @if (TempData["Success"] != null)
        {
            <div class="alert alert-success animate__animated animate__fadeIn">@TempData["Success"]</div>
        }
        @if (TempData["Error"] != null)
        {
            <div class="alert alert-danger animate__animated animate__fadeIn">@TempData["Error"]</div>
        }

        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="VillaNumber.Villa_Number" hidden/>
            <div class="p-3">
                <h5 class="text-muted">Villa Details</h5>
                <hr />

                <div class="form-floating mb-3 col-12 animate__animated animate__fadeIn">
                    <select disabled asp-for="VillaNumber.VillaId" asp-items="Model.Villalist" class="form-select border shadow">
                        <option disabled selected style="color:gray;">Select Villa</option>
                    </select>
                    <label asp-for="VillaNumber.VillaId" class="ms-2"></label>
                    <span asp-validation-for="VillaNumber.VillaId" class="text-danger"></span>
                </div>

                <div class="form-floating mb-3 col-12 animate__animated animate__fadeIn">
                    <input disabled asp-for="VillaNumber.Villa_Number" class="form-control border shadow" title="Enter the unique Villa Number" />
                    <label asp-for="VillaNumber.Villa_Number" class="ms-2"></label>
                    <span asp-validation-for="VillaNumber.Villa_Number" class="text-danger"></span>
                </div>

                <div class="form-floating mb-3 col-12 animate__animated animate__fadeIn">
                    <input disabled asp-for="VillaNumber.SpecialDetails" class="form-control border shadow" title="Enter any special instructions or features" />
                    <label asp-for="VillaNumber.SpecialDetails" class="ms-2"></label>
                    <span asp-validation-for="VillaNumber.SpecialDetails" class="text-danger"></span>
                </div>

                <div class="row pt-3">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100">
                            <i class="bi bi-check-circle"></i> Delete
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="VillaNumber" asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle"></i> Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Villa_project/Views/VillaNumber/Index.cshtml
@model IEnumerable<VillaNumber>
<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Villa List</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <div class="row pb-3">
            <div class="col-6 offset-6 text-end">
                <a asp-controller="VillaNumber" asp-action="Create" class="btn btn-secondary">
                    <i class="bi bi-plus-circle"></i> Create New VillaNumber
                </a>
            </div>
        </div>

        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>
                        Villa Name
                    </th>
                    <th>Villa Number</th>
                    <th>Special Detail</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td>@obj.Villa.Name</td>
                        <td>@obj.Villa_Number</td>
                        <td>@obj.SpecialDetails</td>
                        
                        <td>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="VillaNumber" asp-action="Update" asp-route-villaId="@obj.Villa_Number"
                                   class="btn btn-success mx-2">
                                    <i class="bi bi-pencil-square"></i> Edit
                                </a>
                                <a asp-controller="VillaNumber" asp-action="Delete" asp-route-villaId="@obj.Villa_Number"
                                   class="btn btn-danger mx-2">
                                    <i class="bi bi-trash-fill"></i> Delete
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Villa_project/Views/VillaNumber/Update.cshtml
@model Villa_project.ViewModels.VillaNumberVM

@{
    ViewData["Title"] = "Update Villa Number";
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />

<div class="w-100 card border-0 p-4 shadow-lg rounded">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2 text-uppercase">Update Villa</h2>
            </div>
        </div>
    </div>

    <div class="card-body border p-4">
        @if (TempData["Success"] != null)
        {
            <div class="alert alert-success animate__animated animate__fadeIn">@TempData["Success"]</div>
        }
        @if (TempData["Error"] != null)
        {
            <div class="alert alert-danger animate__animated animate__fadeIn">@TempData["Error"]</div>
        }

        <form method="post" class="row" enctype="multipart/form-data">
            <input asp-for="VillaNumber.Villa_Number" hidden />
            <div class="p-3">
                <h5 class="text-muted">Villa Details</h5>
                <hr />

                <div class="form-floating mb-3 col-12 animate__animated animate__fadeIn">
                    <select asp-for="VillaNumber.VillaId" asp-items="Model.Villalist" class="form-select border shadow">
                        <option  selected style="color:gray;">Select Villa</option>
                    </select>
                    <label asp-for="VillaNumber.VillaId" class="ms-2"></label>
                    <span asp-validation-for="VillaNumber.VillaId" class="text-danger"></span>
                </div>

                <div class="form-floating mb-3 col-12 animate__animated animate__fadeIn">
                    <input asp-for="VillaNumber.Villa_Number" class="form-control border shadow" title="Enter the unique Villa Number" />
                    <label asp-for="VillaNumber.Villa_Number" class="ms-2"></label>
                    <span asp-validation-for="VillaNumber.Villa_Number" class="text-danger"></span>
                </div>

                <div class="form-floating mb-3 col-12 animate__animated animate__fadeIn">
                    <input asp-for="VillaNumber.SpecialDetails" class="form-control border shadow" title="Enter any special instructions or features" />
                    <label asp-for="VillaNumber.SpecialDetails" class="ms-2"></label>
                    <span asp-validation-for="VillaNumber.SpecialDetails" class="text-danger"></span>
                </div>

                <div class="row pt-3">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100">
                            <i class="bi bi-check-circle"></i> Update
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="VillaNumber" asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle"></i> Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}